### ISSUE TITLE
Can you consider adding Chinese support?

### ISSUE THREAD

**Issue by weakish** [koron/cmigemo#15]
Here is [a dictionary file for Chinese](https://github.com/weakish/migemo-dict-zh/blob/master/migemo-dict-zh).

It works with `cmigemo -d`.

Do you have interest to include it in cmigemo as a built-in dictionary?

**Comment by koron** [comment]
Please make a PR to including Chinese dictionary.

**Comment by koron** [comment]
answered.

**Comment by weakish** [comment]
>> answered.

@koron What do you mean by 'answered'? Do I need to make a PR?

**Comment by koron** [comment]
@weakish 

Sorry to cofusing you.

"answered" is just a mark for me.  It means "I had answered to this question"

And that answer is: I'll please to merge PR which include Chinese dictionary, if you (or anyone) create it.

**Comment by koron** [comment]
I have reopened this because PR #23 is made.

**Comment by koron** [comment]
included Chinese dictionary already
