### ISSUE TITLE
Migemo should perform exact match first: "nat" and "Nat"

### ISSUE THREAD

**Issue by knu** [koron/cmigemo#19]
Migemo generates the following pattern from a query "nat", which (in case-insensitive search) will match only "na" out of a string "nat" because "Na" appears earlier than "nat".

```
% cmigemo -d /usr/local/share/migemo/utf-8/migemo-dict -w nat
([棘棗懷捺懐夏鉈屶釶]|納[得豆音]|Sodium|Na|無月|長束|奈[月津]|那(智|津子)|ﾅ([ﾄﾃﾂﾁﾀ]|ｯ[ﾄﾃﾂﾁﾀ])|名([取谷]|田庄)|菜[摘種]|な([とてつちた]|っ[とてつちた])|ｎａｔ|Ｎａｔｕｒｅ|ネ(ー(ティブ|ション)|イ(ト|サン|チャー|ティ[ヴブ]|ション))|ナ([テツタトチ]|ータン|サニエル|シ(オン|ョナ(ル|リ(ティ|スト|ズム)))|ッ[テツチタト])|nat)
```

Now, if I give a query "Nat", Migemo returns a pattern that does not match the string itself.

```
% cmigemo -d /usr/local/share/migemo/utf-8/migemo-dict -w Nat
([棘棗懷捺懐夏鉈屶釶]|納[得豆音]|Sodium|無月|長束|奈[月津]|那(智|津子)|ﾅ([ﾄﾃﾂﾁﾀ]|ｯ[ﾄﾃﾂﾁﾀ])|名([取谷]|田庄)|菜[摘種]|な([とてつちた]|っ[とてつちた])|Ｎａｔ|ネ(ー(ティブ|ション)|イ(ト|サン|チャー|ティ[ ヴブ]|ション))|ナ([テツタトチ]|ータン|サニエル|シ(オン|ョナ(ル|リ(ティ|スト|ズム)))|ッ[テツチタト])|Na)
```

I'd expect any query would match the exact string itself.

**Comment by knu** [comment]
While it may be easier to fix this by adjusting the order of candidates, I guess substrings (or just prefixes) of a query should probably be excluded when compiling a pattern.  What do you think?

**Comment by koron** [comment]
I have no idea for now.

> substrings (or just prefixes) of a query should probably be excluded when compiling a pattern

But it seems not-good idea, because perfoming excluding checks against all candidates will cause perfomance issue.

**Comment by koron** [comment]
How about removing "Nature" from dictionary?

**Comment by koron** [comment]
Try to remove this entry from SKK-JISYO.utf-8.L

```
なとりうむ /Na/Sodium/
```

**Comment by knu** [comment]
I'm not fond of altering the dictionary by hand when the problem looks algorithmically solvable.

I don't know a thing about the algorithms used by Migemo, but thought there might already be some kind of ordering and prefix testing against candidates.  I wonder where the difference in the above patterns, namely the position of "Na" comes from.  If that is related to the word "Na" being a prefix of "Nat", there should be a room for tweaking the implementation.  Hope I'll be able to take the time and look into this later this month.

**Comment by koron** [comment]
> I wonder where the difference in the above patterns, namely the position of "Na" comes from.

It is this.

```
なとりうむ /Na/Sodium/
```

`nat` matches with `なとりうむ` and it is expanded to `Na` and `Sodium`.

**Comment by koron** [comment]
There are no good solution for now.  So I put `wontfix` label.
It would be removed when good solution is suggested.

**Comment by knu** [comment]
I know.  Both "Nat" and "nat" should match "なとりうむ" and that is why "Na" and "Sodium" appear in both produced patterns, but that does not explain why the pattern produced from "Nat" does not contain "Nat" while the one produced from "nat" contains "nat".

**Comment by knu** [comment]
OK, I'll try tackling this myself, thanks for taking the time!

**Comment by koron** [comment]
close until good solution found
